<script>
	let name = 'world';
</script>

<main>
	<argdown-map>
		<div slot="map">
			<!-- Generated by graphviz version 2.40.1 (20161225.0304)
-->
			<!-- Title: Argument Map Pages: 1 -->
			<svg
				width="418pt"
				height="124pt"
				viewBox="0.00 0.00 418.00 124.00"
				xmlns="http://www.w3.org/2000/svg"
				xmlns:xlink="http://www.w3.org/1999/xlink"
			>
				<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 120)">
					<title>Argument Map</title>
					<!-- n0 -->
					<g id="node1" class="node">
						<title>n0</title>
						<path
							fill="#ffffff"
							stroke="#1b9e77"
							stroke-width="2"
							d="M184,-40C184,-40 12,-40 12,-40 6,-40 0,-34 0,-28 0,-28 0,-12 0,-12 0,-6 6,0 12,0 12,0 184,0 184,0 190,0 196,-6 196,-12 196,-12 196,-28 196,-28 196,-34 190,-40 184,-40"
						/>
						<text
							text-anchor="start"
							x="94.6655"
							y="-26"
							font-family="arial"
							font-weight="bold"
							font-size="10.00"
							fill="#000000"
						>
							B
						</text>
						<text
							text-anchor="start"
							x="89.9415"
							y="-9"
							font-family="arial"
							font-size="10.00"
							fill="#000000"
						>
							test
						</text>
					</g>
					<!-- n1 -->
					<g id="node2" class="node">
						<title>n1</title>
						<path
							fill="#1b9e77"
							stroke="#000000"
							d="M291,-116C291,-116 119,-116 119,-116 113,-116 107,-110 107,-104 107,-104 107,-88 107,-88 107,-82 113,-76 119,-76 119,-76 291,-76 291,-76 297,-76 303,-82 303,-88 303,-88 303,-104 303,-104 303,-110 297,-116 291,-116"
						/>
						<text
							text-anchor="start"
							x="201.6655"
							y="-102"
							font-family="arial"
							font-weight="bold"
							font-size="10.00"
							fill="#000000"
						>
							A
						</text>
						<text
							text-anchor="start"
							x="196.9415"
							y="-85"
							font-family="arial"
							font-size="10.00"
							fill="#000000"
						>
							test
						</text>
					</g>
					<!-- n0&#45;&gt;n1 -->
					<g id="edge1" class="edge">
						<title>n0&#45;&gt;n1</title>
						<path
							fill="none"
							stroke="#ff0000"
							d="M126.3931,-40.1671C139.211,-49.2713 154.5155,-60.1418 168.1998,-69.8616"
						/>
						<polygon
							fill="#ff0000"
							stroke="#ff0000"
							points="166.2947,-72.8014 176.4742,-75.7387 170.3482,-67.0944 166.2947,-72.8014"
						/>
					</g>
					<!-- n2 -->
					<g id="node3" class="node">
						<title>n2</title>
						<path
							fill="#1b9e77"
							stroke="#000000"
							d="M398,-40C398,-40 226,-40 226,-40 220,-40 214,-34 214,-28 214,-28 214,-12 214,-12 214,-6 220,0 226,0 226,0 398,0 398,0 404,0 410,-6 410,-12 410,-12 410,-28 410,-28 410,-34 404,-40 398,-40"
						/>
						<text
							text-anchor="start"
							x="308.3905"
							y="-26"
							font-family="arial"
							font-weight="bold"
							font-size="10.00"
							fill="#000000"
						>
							C
						</text>
						<text
							text-anchor="start"
							x="303.9415"
							y="-9"
							font-family="arial"
							font-size="10.00"
							fill="#000000"
						>
							test
						</text>
					</g>
					<!-- n2&#45;&gt;n1 -->
					<g id="edge2" class="edge">
						<title>n2&#45;&gt;n1</title>
						<path
							fill="none"
							stroke="#00ff00"
							d="M283.6069,-40.1671C270.789,-49.2713 255.4845,-60.1418 241.8002,-69.8616"
						/>
						<polygon
							fill="#00ff00"
							stroke="#00ff00"
							points="239.6518,-67.0944 233.5258,-75.7387 243.7053,-72.8014 239.6518,-67.0944"
						/>
					</g>
				</g>
			</svg>
		</div>
		<div slot="source">
			<pre><code class="language-argdown">
    <span class="token statement class-name"
						><span class="token punctuation">[</span>B<span class="token punctuation">]</span><span
							class="token punctuation">:</span
						></span
					> test

    <span class="token argument class-name"
						><span class="token punctuation">&lt;</span>A<span class="token punctuation">></span
						><span class="token punctuation">:</span></span
					> test
        <span class="token attack operator">-</span> <span class="token statement class-name"
						><span
							class="token
punctuation">[</span
						>B<span class="token punctuation">]</span></span
					>
        <span class="token support operator">+</span> <span class="token argument class-name"
						><span
							class="token
punctuation">&lt;</span
						>C<span class="token punctuation">></span><span class="token punctuation">:</span></span
					> test        </code></pre>
		</div>
	</argdown-map>
</main>
