<!-- Generated by graphviz version 2.47.0 (20210316.0004)
 -->
<!-- Title: Argument Map Pages: 1 -->
<svg
	width="418pt"
	height="160pt"
	viewBox="0.00 0.00 418.00 160.00"
	xmlns="http://www.w3.org/2000/svg"
	xmlns:xlink="http://www.w3.org/1999/xlink"
>
	<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 156)">
		<title>Argument Map</title>
		<!-- n0 -->
		<g id="node1" class="node">
			<title>n0</title>
			<path
				fill="white"
				stroke="#1b9e77"
				stroke-width="2"
				d="M291,-40C291,-40 119,-40 119,-40 113,-40 107,-34 107,-28 107,-28 107,-12 107,-12 107,-6 113,0 119,0 119,0 291,0 291,0 297,0 303,-6 303,-12 303,-12 303,-28 303,-28 303,-34 297,-40 291,-40"
			/>
			<text
				text-anchor="start"
				x="178.05"
				y="-26"
				font-family="arial"
				font-weight="bold"
				font-size="10.00"
				fill="#000000">Statement 1</text
			>
			<text
				text-anchor="start"
				x="196.94"
				y="-9"
				font-family="arial"
				font-size="10.00"
				fill="#000000">text</text
			>
		</g>
		<!-- n1 -->
		<g id="node2" class="node">
			<title>n1</title>
			<path
				fill="white"
				stroke="#1b9e77"
				stroke-width="2"
				d="M184,-152C184,-152 12,-152 12,-152 6,-152 0,-146 0,-140 0,-140 0,-124 0,-124 0,-118 6,-112 12,-112 12,-112 184,-112 184,-112 190,-112 196,-118 196,-124 196,-124 196,-140 196,-140 196,-146 190,-152 184,-152"
			/>
			<text
				text-anchor="start"
				x="71.05"
				y="-138"
				font-family="arial"
				font-weight="bold"
				font-size="10.00"
				fill="#000000">Statement 2</text
			>
			<text
				text-anchor="start"
				x="89.94"
				y="-121"
				font-family="arial"
				font-size="10.00"
				fill="#000000">text</text
			>
		</g>
		<!-- n1&#45;&gt;n0 -->
		<g id="edge1" class="edge">
			<title>n1&#45;&gt;n0</title>
			<path
				fill="none"
				stroke="#00ff00"
				d="M116.64,-111.84C133.95,-94.05 159.88,-67.39 179.18,-47.55"
			/>
			<polygon
				fill="#00ff00"
				stroke="#00ff00"
				points="181.75,-49.92 186.22,-40.31 176.74,-45.04 181.75,-49.92"
			/>
		</g>
		<!-- n2 -->
		<g id="node3" class="node">
			<title>n2</title>
			<path
				fill="white"
				stroke="#1b9e77"
				stroke-width="2"
				d="M398,-152C398,-152 226,-152 226,-152 220,-152 214,-146 214,-140 214,-140 214,-124 214,-124 214,-118 220,-112 226,-112 226,-112 398,-112 398,-112 404,-112 410,-118 410,-124 410,-124 410,-140 410,-140 410,-146 404,-152 398,-152"
			/>
			<text
				text-anchor="start"
				x="285.05"
				y="-138"
				font-family="arial"
				font-weight="bold"
				font-size="10.00"
				fill="#000000">Statement 3</text
			>
			<text
				text-anchor="start"
				x="303.94"
				y="-121"
				font-family="arial"
				font-size="10.00"
				fill="#000000">text</text
			>
		</g>
		<!-- n2&#45;&gt;n0 -->
		<g id="edge2" class="edge">
			<title>n2&#45;&gt;n0</title>
			<path
				fill="none"
				stroke="#ff0000"
				d="M286.34,-104.62C269.63,-87.45 247.91,-65.11 231.12,-47.85"
			/>
			<polygon
				fill="#ff0000"
				stroke="#ff0000"
				points="283.88,-107.11 293.36,-111.84 288.9,-102.23 283.88,-107.11"
			/>
			<polygon
				fill="#ff0000"
				stroke="#ff0000"
				points="233.26,-45.04 223.78,-40.31 228.25,-49.92 233.26,-45.04"
			/>
		</g>
	</g>
</svg>
